services:
  virtual-assistant:
    image: virtual-assistant
    build: .
    container_name: virtual-assistant
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: ["gpu"]
